### PR TITLE
Add eslint & syncpack & lint-staged

### PR DESCRIPTION
**Pull request by arminbenard**
Added syncpack and eslint configuration
- I had to refactor the `next` folder to `next-app` to avoid syncpack mixing up the workspace `next` and the package `next`
- removed the `api/auth` folder as it is a deprecated version and vill be rebuilded with the wp plugin (it needed too much refactoring)

resolves CU-86bzw8cdd

### CODE REVIEW

**Comment by arminbenard** [comment]
Task linked: [CU-86bzw8cdd Add eslint](https://app.clickup.com/t/86bzw8cdd)

**Comment by arminbenard** [comment]
Suggested changes by @tom3rr 
- Merge eslint and ts config
- lint command in root
- check syncpack format in package.json

**Comment by tom3rr** [comment]
@arminbenard please make sure to ignore all node_modules and other local folders when running lint.

**Comment by tom3rr** [comment]
I've added minor fixes in package.json, updated dependencies with syncpack and fixed mismatches.

**Review by tom3rr — CHANGES_REQUESTED** [review]
Syncpack, eslint and lint-staged are properly configured.

Now that linting is configured, the code errors need to be fixed so the next-app can build successfully.
Make sure that the `yarn types`, `yarn lint` and `yarn build` commands are able to run successfully.

This is PR has now reached **URGENT** priority level.

**Pull request merged**
