### PR TITLE
Add starter template home

### PR DESCRIPTION
**Pull request by arminbenard**

### CODE REVIEW

**Comment by tom3rr** [comment]
This is what I get when the backend is not running:
image

The inactive scrollbar is not needed, and the open wordpress button should be disabled if the backend is not running as we discussed.

Afterwards if the backend is running but with a normal theme, I don't see any posts (the original post I deleted and I only have posts I have created):
image

When I activated the Project theme, the page freezes and in the backend log wordpress gets into an infinite request loop:
wordpress-1   | 172.18.0.5 -  15/Aug/2024:14:13:45 +0000 "GET /index.php" 302

Any idea what could be going on?

**Review by tom3rr — CHANGES_REQUESTED** [review]
Experiencing unexpected behaviors as written in the comment.

**Comment by arminbenard** [comment]
@tom3rr I think most of the issues are related to the cache, for example, this is what I see when the backend is not running, and also when the theme is not activated, I didn't manage to get to the state described:
image
I noticed some minor style issues, I fixed those in the meantime.

I couldn't reproduce the errors with the error handling and the infinite loop you described, can you provide more context how you got there? Maybe this is browser/platform related? 

Also I didn't realize how different the scollbar is on Windows, but it should be hidden now 😄

**Review by tom3rr — CHANGES_REQUESTED** [review]
The button is now properly disabled. Styling wise on my screen, although no scrollbar is there, the div is scrollable, but not in the best way:

image

Can you please make the whole page scrollable properly and have the background fixed as the screen size?

If a new wordpress is running but not yet installed, I still get the "open admin" button and not the "setup wordpress" button.

After it is installed, but the theme is not set, the error is there. If the theme is set again, I see no posts.

This is on a fresh image, fresh db. What am I missing?

**Comment by arminbenard** [comment]
@tom3rr I think I found the main reason for the different behaviours for our WordPress installations, I used a command line tool insead of Docker desktop, I didn't have any problems with it in the past year I've using it, but after I changed to Docker desktop as a test, I was able to reproduce the errors above.

This is what I fixed:
- fixed the infinite loop when activating the theme
- added more appropriate error messages (the cache is still an issue, even with `force-dynamic` so the page has to be reloaded to display the true state of the WordPress install)
- refactored the layout to a fixed bg and scrollable page
- other minor style and layout improvements

Let me know if you still experience some errors or if you still see some areas to improve 😄

**Review by tom3rr — APPROVED** [review]
Fixed some underlying issues and fine-tuned some styles. Ready for merge.

**Pull request merged**
